plugins {
    id 'com.android.application'
}

android {
    namespace 'tech.nosmo.nexus.workmode'
    compileSdk 35

    defaultConfig {
        applicationId 'tech.nosmo.nexus.workmode'
        minSdk 26
        targetSdk 35
        versionCode 15
        versionName '0.5.6-work-layer-vacuum'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.nativebeta'
            versionNameSuffix '-beta'
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
