// @ts-ignore -- runtime smoke intentionally uses Node assert without adding ambient Node types to the root core contract.
import assert from 'node:assert/strict';
import { emptyProjectMemorySnapshot } from '../../data/projectMemory';

declare const console: { log(...args: unknown[]): void };
import type { NexusCanonicalAuthorityEvaluation, NexusCanonicalAuthorityRequest } from '../permissions/canonicalAuthorityContract';
import { CanonicalWorkPackageService, makeAllowedAuthorityEvaluation } from './canonicalWorkPackageService';
import { NEXUS_SEMANTIC_OPERATION_SCHEMA, type NexusSemanticOperationRequest } from './canonicalWorkPackageContract';

const SESSION = { providerKey: 'test', providerSubjectDigest: 'a'.repeat(64) };
const PROJECT = 'project-c2'; const WORLD = 'world-c2'; const MANAGER = 'person-manager'; const WORKER = 'person-worker'; const WORKER_2 = 'person-worker-2';
const TASK_1 = 'task-1'; const TASK_2 = 'task-2'; const DOCUMENT_1 = 'document-1'; const OBJECT_1 = 'object-1'; const PACKAGE = 'package-1';
const NOW = '2026-09-08T15:00:00.000Z'; const DEADLINE = '2026-09-30T16:00:00.000Z';

class FakeAuthority {
  revision = 'authority-r1'; denyAuthorize = false; staleOnCommit = false;
  async authorize(request: NexusCanonicalAuthorityRequest): Promise<NexusCanonicalAuthorityEvaluation> {
    const allowed = makeAllowedAuthorityEvaluation({ request, personId: MANAGER, authorityRevision: this.revision });
    if (!this.denyAuthorize) return allowed;
    return { ...allowed, status: 'DENIED', reasonCode: 'EXPLICIT_DENY', allowed: false, actor: allowed.actor ? { ...allowed.actor, status: 'DENIED', reasonCode: 'EXPLICIT_DENY' } : undefined };
  }
  async recheckForCommit(request: NexusCanonicalAuthorityRequest, expectedAuthorityRevision: string): Promise<NexusCanonicalAuthorityEvaluation> {
    if (this.staleOnCommit) { const current = makeAllowedAuthorityEvaluation({ request, personId: MANAGER, authorityRevision: `${expectedAuthorityRevision}-changed` }); return { ...current, status: 'STALE', reasonCode: 'AUTHORITY_REVISION_STALE', allowed: false, currentStatusBeforeStale: 'ALLOWED' }; }
    return makeAllowedAuthorityEvaluation({ request, personId: MANAGER, authorityRevision: expectedAuthorityRevision });
  }
}

const memoryFixture = () => {
  const memory = emptyProjectMemorySnapshot();
  memory.projects.push({ id: PROJECT, status: 'active' } as any); memory.worlds.push({ id: WORLD, status: 'active', projectId: PROJECT } as any);
  memory.people.push({ id: MANAGER, status: 'active' } as any, { id: WORKER, status: 'active' } as any, { id: WORKER_2, status: 'active' } as any);
  memory.tasks.push(
    { id: TASK_1, status: 'active', title: 'Inspect door', projectId: PROJECT, worldId: WORLD, taskStatus: 'todo', priority: 'normal', assignedPersonIds: [], createdAt: NOW, updatedAt: NOW, sourceSystem: 'nexus', confidence: 'confirmed' } as any,
    { id: TASK_2, status: 'active', title: 'Second task', projectId: PROJECT, worldId: WORLD, taskStatus: 'todo', priority: 'normal', assignedPersonIds: [], createdAt: NOW, updatedAt: NOW, sourceSystem: 'nexus', confidence: 'confirmed' } as any,
    { id: 'task-other-world', status: 'active', title: 'Wrong scope task', projectId: PROJECT, worldId: 'world-other', taskStatus: 'todo', priority: 'normal', assignedPersonIds: [], createdAt: NOW, updatedAt: NOW, sourceSystem: 'nexus', confidence: 'confirmed' } as any,
  );
  memory.files.push({ id: DOCUMENT_1, status: 'active', title: 'Fire strategy', projectId: PROJECT, worldId: WORLD, fileKind: 'pdf', documentClass: 'report', storageConnectorId: 'synthetic', createdAt: NOW, updatedAt: NOW, sourceSystem: 'nexus', confidence: 'confirmed' } as any);
  memory.canonicalObjects.push({ id: OBJECT_1, status: 'active', title: 'Door A-101', projectId: PROJECT, worldId: WORLD, lifecycleStatus: 'active', externalReferenceIds: [], createdAt: NOW, updatedAt: NOW, sourceSystem: 'nexus', confidence: 'confirmed' } as any);
  for (const [personId, participationId] of [[MANAGER, 'part-manager'], [WORKER, 'part-worker'], [WORKER_2, 'part-worker-2']] as const) memory.projectParticipations.push({ id: participationId, status: 'active', title: participationId, personId, projectId: PROJECT, worldId: WORLD, participationStatus: 'active', roleAssignmentIds: [], tradeAssignmentIds: [], permissionGrantIds: [], approvalScopeIds: [], competenceRequirementIds: [], createdAt: NOW, updatedAt: NOW, sourceSystem: 'nexus', confidence: 'confirmed' } as any);
  return memory;
};
const op = (input: Omit<NexusSemanticOperationRequest, 'schema' | 'session' | 'workspaceId' | 'projectId' | 'worldId' | 'occurredAt'> & Partial<Pick<NexusSemanticOperationRequest, 'occurredAt'>>): NexusSemanticOperationRequest => ({ schema: NEXUS_SEMANTIC_OPERATION_SCHEMA, session: SESSION, workspaceId: 1, projectId: PROJECT, worldId: WORLD, occurredAt: input.occurredAt ?? NOW, ...input });
const expectCompanionInvalid = async (service: CanonicalWorkPackageService, request: NexusSemanticOperationRequest): Promise<void> => { const result = await service.validateSemanticOperation(request); assert.equal(result.status, 'INVALID'); if (result.status === 'INVALID') assert.ok(result.failures.some((item) => item.code === 'COMPANION_GRANT_INVALID')); };

const companionRegression = async (): Promise<void> => {
  const service = new CanonicalWorkPackageService(new FakeAuthority(), memoryFixture()); const packageId = 'package-grantable';
  const composed = await service.composeWorkPackage({ packageId, session: SESSION, workspaceId: 1, projectId: PROJECT, worldId: WORLD, occurredAt: NOW, title: 'Grantable package', items: [{ itemId: 'grantable-item', order: 1, kind: 'APP', title: 'DoorFlow access', required: true, appId: 'app-doorflow', targetCapabilityRequirements: [{ moduleId: 'doorflow', actionKey: 'doorflow.open', objectScopeId: OBJECT_1, dataScope: 'door:A-101', accessMode: 'GRANTABLE_IN_SAME_OPERATION', companionGrantIntentId: 'wp-companion-intent' }] }] }); assert.equal(composed.status, 'APPLIED');
  const base = op({ semanticOperationId: 'op-wp-grantable', intent: 'WORK_PACKAGE_TO_PERSON', source: { type: 'WORK_PACKAGE', id: packageId }, target: { type: 'PERSON', id: WORKER }, packageId, expectedPackageRevision: 1 });
  await expectCompanionInvalid(service, base);
  await expectCompanionInvalid(service, { ...base, companionGrants: [] });
  await expectCompanionInvalid(service, { ...base, companionGrants: [{ intentId: 'wp-companion-intent', grantId: 'wp-grant-wrong-action', moduleId: 'doorflow', actionKey: 'doorflow.close', objectScopeId: OBJECT_1, dataScope: 'door:A-101', reason: 'wrong action' }] });
  await expectCompanionInvalid(service, { ...base, companionGrants: [{ intentId: 'wp-companion-intent', grantId: 'wp-grant-wrong-object', moduleId: 'doorflow', actionKey: 'doorflow.open', objectScopeId: 'object-other', dataScope: 'door:A-101', reason: 'wrong object' }] });
  const matching = { ...base, companionGrants: [{ intentId: 'wp-companion-intent', grantId: 'wp-grant-exact', moduleId: 'doorflow', actionKey: 'doorflow.open', objectScopeId: OBJECT_1, dataScope: 'door:A-101', reason: 'Required by assigned Work Package.' }] };
  const validation = await service.validateSemanticOperation(matching); assert.equal(validation.status, 'VALID'); if (validation.status === 'VALID') assert.ok(validation.plan.effects.some((effect) => effect.type === 'COMPANION_PERMISSION_GRANT' && effect.grantId === 'wp-grant-exact'));
  const committed = await service.commitSemanticOperation(matching, validation); assert.equal(committed.status, 'COMMITTED'); assert.ok(committed.assignment); assert.equal(service.getMemory().permissionGrants.filter((grant) => grant.id === 'wp-grant-exact').length, 1); assert.ok(service.getMemory().projectParticipations.find((p) => p.personId === WORKER)?.permissionGrantIds.includes('wp-grant-exact'));
  assert.equal((await service.commitSemanticOperation(matching)).status, 'ALREADY_COMMITTED'); assert.equal(service.getMemory().permissionGrants.filter((grant) => grant.id === 'wp-grant-exact').length, 1); assert.equal(service.listAssignments(packageId).length, 1);
  const mismatch = { ...matching, companionGrants: [{ ...matching.companionGrants![0]!, actionKey: 'doorflow.close' }] }; assert.equal((await service.commitSemanticOperation(mismatch)).status, 'IDEMPOTENCY_CONFLICT');
  const concurrentService = new CanonicalWorkPackageService(new FakeAuthority(), memoryFixture()); const concurrentPackage = 'package-grantable-concurrent'; const concurrentCompose = await concurrentService.composeWorkPackage({ packageId: concurrentPackage, session: SESSION, workspaceId: 1, projectId: PROJECT, worldId: WORLD, occurredAt: NOW, title: 'Concurrent grantable package', items: [{ itemId: 'grantable-item', order: 1, kind: 'APP', title: 'DoorFlow access', required: true, appId: 'app-doorflow', targetCapabilityRequirements: [{ moduleId: 'doorflow', actionKey: 'doorflow.open', objectScopeId: OBJECT_1, accessMode: 'GRANTABLE_IN_SAME_OPERATION', companionGrantIntentId: 'wp-concurrent-intent' }] }] }); assert.equal(concurrentCompose.status, 'APPLIED');
  const concurrentRequest = op({ semanticOperationId: 'op-wp-grantable-concurrent', intent: 'WORK_PACKAGE_TO_PERSON', source: { type: 'WORK_PACKAGE', id: concurrentPackage }, target: { type: 'PERSON', id: WORKER_2 }, packageId: concurrentPackage, expectedPackageRevision: 1, companionGrants: [{ intentId: 'wp-concurrent-intent', grantId: 'wp-grant-concurrent', moduleId: 'doorflow', actionKey: 'doorflow.open', objectScopeId: OBJECT_1, reason: 'Concurrent exact retry.' }] });
  const concurrent = await Promise.all([concurrentService.commitSemanticOperation(concurrentRequest), concurrentService.commitSemanticOperation(concurrentRequest)]); assert.deepEqual(concurrent.map((result) => result.status).sort(), ['ALREADY_COMMITTED', 'COMMITTED']); assert.equal(concurrentService.listAssignments(concurrentPackage).length, 1); assert.equal(concurrentService.getMemory().permissionGrants.filter((grant) => grant.id === 'wp-grant-concurrent').length, 1);
};

const main = async (): Promise<void> => {
  await companionRegression();
  const authority = new FakeAuthority(); const service = new CanonicalWorkPackageService(authority, memoryFixture());
  const composed = await service.composeWorkPackage({ packageId: PACKAGE, session: SESSION, workspaceId: 1, projectId: PROJECT, worldId: WORLD, occurredAt: NOW, title: 'Door inspection package', deadline: DEADLINE, groups: [{ groupId: 'group-a', order: 1, title: 'Inspection' }, { groupId: 'group-b', order: 2, title: 'Closeout' }], items: [{ itemId: 'item-task-1', order: 1, groupId: 'group-a', kind: 'TASK', title: 'Task one', required: true, taskId: TASK_1 }, { itemId: 'item-task-2', order: 2, groupId: 'group-a', kind: 'TASK', title: 'Task two', required: false, taskId: TASK_2 }, { itemId: 'item-checklist', order: 3, groupId: 'group-b', kind: 'CHECKLIST', title: 'Checklist', required: true, checklistId: 'checklist-1', taskId: TASK_1 }, { itemId: 'item-evidence', order: 4, groupId: 'group-b', kind: 'EVIDENCE_REQUIREMENT', title: 'Photo evidence', required: true, evidenceRequirementId: 'req-photo', taskId: TASK_1 }], checklistDefinitions: [{ checklistId: 'checklist-1', revision: 1, title: 'Door checks', items: [{ itemId: 'check-item-1', order: 1, title: 'Door closes', required: true, expectedResponseType: 'BOOLEAN' }, { itemId: 'check-item-2', order: 2, title: 'Comment', required: false, expectedResponseType: 'TEXT' }] }], evidenceRequirements: [{ requirementId: 'req-photo', kind: 'PHOTO_PROOF', taskId: TASK_1, workPackageId: PACKAGE, requiredCount: 1, allowedEvidenceType: 'photo', description: 'One photo before finish', requiredBeforeFinish: true }] });
  assert.equal(composed.status, 'APPLIED'); assert.equal(service.listAssignments(PACKAGE).length, 0); if (composed.status !== 'APPLIED') throw new Error('compose failed'); assert.equal(composed.workPackage.revision, 1); assert.equal(composed.workPackage.items.filter((item) => item.kind === 'TASK').length, 2);
  const staleEdit = await service.reviseWorkPackage({ packageId: PACKAGE, expectedRevision: 0, session: SESSION, occurredAt: NOW, title: 'stale' }); assert.equal(staleEdit.status, 'BLOCKED');
  const revised = await service.reviseWorkPackage({ packageId: PACKAGE, expectedRevision: 1, session: SESSION, occurredAt: '2026-09-08T15:05:00.000Z', groups: [{ groupId: 'group-b', order: 1, title: 'Closeout' }, { groupId: 'group-a', order: 2, title: 'Inspection' }], items: [{ itemId: 'item-checklist', order: 1, groupId: 'group-b', kind: 'CHECKLIST', title: 'Checklist', required: true, checklistId: 'checklist-1', taskId: TASK_1 }, { itemId: 'item-evidence', order: 2, groupId: 'group-b', kind: 'EVIDENCE_REQUIREMENT', title: 'Photo evidence', required: true, evidenceRequirementId: 'req-photo', taskId: TASK_1 }, { itemId: 'item-task-2', order: 3, groupId: 'group-a', kind: 'TASK', title: 'Task two', required: false, taskId: TASK_2 }, { itemId: 'item-task-1', order: 4, groupId: 'group-a', kind: 'TASK', title: 'Task one', required: true, taskId: TASK_1 }] }); assert.equal(revised.status, 'APPLIED'); if (revised.status !== 'APPLIED') throw new Error('revise failed');
  const wpPersonRequest = op({ semanticOperationId: 'op-wp-person', intent: 'WORK_PACKAGE_TO_PERSON', source: { type: 'WORK_PACKAGE', id: PACKAGE }, target: { type: 'PERSON', id: WORKER }, packageId: PACKAGE, expectedPackageRevision: 2 }); const wpPersonCommit = await service.commitSemanticOperation(wpPersonRequest); assert.equal(wpPersonCommit.status, 'COMMITTED'); const assignmentId = wpPersonCommit.assignment!.assignmentId;
  const postAssignmentEdit = await service.reviseWorkPackage({ packageId: PACKAGE, expectedRevision: 2, session: SESSION, occurredAt: '2026-09-08T15:10:00.000Z', title: 'Door inspection package v3' }); assert.equal(postAssignmentEdit.status, 'APPLIED');
  const run = service.recordChecklistRun({ runId: 'run-1', assignmentId, taskId: TASK_1, workerPersonId: WORKER, checklistId: 'checklist-1', responses: [{ itemId: 'check-item-1', value: true, respondedAt: NOW }], occurredAt: '2026-09-08T15:15:00.000Z' }); assert.equal(run.status, 'APPLIED');
  const beforeEvidence = service.evidenceRequirementsBeforeFinish({ assignmentId, taskId: TASK_1 }); assert.equal(beforeEvidence.allowed, false); const memoryWithEvidence = service.getMemory(); memoryWithEvidence.evidence.push({ id: 'evidence-photo-1', status: 'active', title: 'Photo', evidenceType: 'photo', evidenceStatus: 'captured', projectId: PROJECT, worldId: WORLD, linkedTaskId: TASK_1, createdAt: NOW, updatedAt: NOW, sourceSystem: 'nexus', confidence: 'confirmed' } as any); service.syncProjectMemory(memoryWithEvidence); assert.equal(service.evidenceRequirementsBeforeFinish({ assignmentId, taskId: TASK_1 }).allowed, true);
  const taskPerson = op({ semanticOperationId: 'op-task-person', intent: 'TASK_TO_PERSON', source: { type: 'TASK', id: TASK_1 }, target: { type: 'PERSON', id: WORKER_2 } }); assert.equal((await service.commitSemanticOperation(taskPerson)).status, 'COMMITTED');
  const documentTask = op({ semanticOperationId: 'op-document-task', intent: 'DOCUMENT_TO_TASK', source: { type: 'DOCUMENT', id: DOCUMENT_1 }, target: { type: 'TASK', id: TASK_1 } }); assert.equal((await service.commitSemanticOperation(documentTask)).status, 'COMMITTED');
  const appPerson = op({ semanticOperationId: 'op-app-person', intent: 'APP_TO_PERSON', source: { type: 'APP', id: 'app-doorflow' }, target: { type: 'PERSON', id: WORKER_2 }, companionGrants: [{ intentId: 'companion-intent-1', grantId: 'permission-grant-app-worker-2', moduleId: 'doorflow', actionKey: 'doorflow.open', objectScopeId: OBJECT_1, reason: 'Required by semantic App -> Person assignment.' }] }); assert.equal((await service.commitSemanticOperation(appPerson)).status, 'COMMITTED');
  const wpObject = op({ semanticOperationId: 'op-wp-object', intent: 'WORK_PACKAGE_TO_OBJECT', source: { type: 'WORK_PACKAGE', id: PACKAGE }, target: { type: 'OBJECT', id: OBJECT_1 }, packageId: PACKAGE, expectedPackageRevision: 3 }); assert.equal((await service.commitSemanticOperation(wpObject)).status, 'COMMITTED');
  assert.equal((await service.commitSemanticOperation(documentTask)).status, 'ALREADY_COMMITTED'); assert.equal((await service.commitSemanticOperation({ ...documentTask, target: { type: 'TASK', id: TASK_2 } })).status, 'IDEMPOTENCY_CONFLICT');
  const concurrent = op({ semanticOperationId: 'op-concurrent-task-person', intent: 'TASK_TO_PERSON', source: { type: 'TASK', id: TASK_2 }, target: { type: 'PERSON', id: WORKER_2 } }); const concurrentResults = await Promise.all([service.commitSemanticOperation(concurrent), service.commitSemanticOperation(concurrent)]); assert.deepEqual(concurrentResults.map((result) => result.status).sort(), ['ALREADY_COMMITTED', 'COMMITTED']);
  authority.denyAuthorize = true; const denied = await service.validateSemanticOperation(op({ semanticOperationId: 'op-denied', intent: 'TASK_TO_PERSON', source: { type: 'TASK', id: TASK_1 }, target: { type: 'PERSON', id: WORKER } })); assert.equal(denied.status, 'INVALID'); authority.denyAuthorize = false;
  const staleRequest = op({ semanticOperationId: 'op-stale-authority', intent: 'TASK_TO_PERSON', source: { type: 'TASK', id: TASK_1 }, target: { type: 'PERSON', id: WORKER } }); const staleValidation = await service.validateSemanticOperation(staleRequest); authority.staleOnCommit = true; const staleCommit = await service.commitSemanticOperation(staleRequest, staleValidation); assert.equal(staleCommit.status, 'BLOCKED'); authority.staleOnCommit = false;
  const rollbackService = new CanonicalWorkPackageService(new FakeAuthority(), memoryFixture(), { beforeSemanticCommitSwap: () => { throw new Error('synthetic persistence failure'); } }); const rollbackRequest = op({ semanticOperationId: 'op-rollback', intent: 'TASK_TO_PERSON', source: { type: 'TASK', id: TASK_1 }, target: { type: 'PERSON', id: WORKER } }); const rollback = await rollbackService.commitSemanticOperation(rollbackRequest); assert.equal(rollback.status, 'BLOCKED'); assert.equal(rollbackService.getMemory().relationshipEdges.length, 0); assert.equal(rollbackService.getMemory().timelineEvents.length, 0);
  console.log('NEXUS_WORK_PACKAGE_CONTRACT_PASS cases=34 companion_grant_regressions=10');
};

void main();