import { ESAFE_SOURCE_FILE_COUNT, ESAFE_SOURCE_RECORD_COUNT } from "./model";

export const ESAFE_EXPECTED_SOURCE_RECORD_COUNT = 95;
export const ESAFE_EXPECTED_SOURCE_FILE_COUNT = 106;

if (ESAFE_SOURCE_RECORD_COUNT !== ESAFE_EXPECTED_SOURCE_RECORD_COUNT) {
  throw new Error(`e-SAFE source record drift: expected ${ESAFE_EXPECTED_SOURCE_RECORD_COUNT}, received ${ESAFE_SOURCE_RECORD_COUNT}`);
}

if (ESAFE_SOURCE_FILE_COUNT !== ESAFE_EXPECTED_SOURCE_FILE_COUNT) {
  throw new Error(`e-SAFE source file drift: expected ${ESAFE_EXPECTED_SOURCE_FILE_COUNT}, received ${ESAFE_SOURCE_FILE_COUNT}`);
}
