import type { NexusConnectorDefinition } from './registryTypes';

export const nexusConnectors: NexusConnectorDefinition[] = [
  {
    id: 'google-drive',
    name: 'Google Drive / Nexus Cloud',
    category: 'cloud-storage',
    status: 'active-reference',
    sourceOfTruth: 'Google Drive project folders',
    nexusRole: 'Project files, drawings, evidence folders, shared documents and cloud navigation.',
    objectLinks: ['ProjectWorld', 'Project', 'File', 'Document', 'Drawing', 'Evidence', 'Task'],
    actions: ['open-folder', 'open-file', 'attach-reference', 'classify-later'],
  },
  {
    id: 'work-wallet',
    name: 'Work Wallet',
    category: 'safety-compliance',
    status: 'reference-layer',
    sourceOfTruth: 'Work Wallet',
    nexusRole: 'Safety status, RAMS, permits, inductions, training and compliance references without copying the source record.',
    objectLinks: ['Person', 'Project', 'Task', 'Evidence', 'Approval'],
    actions: ['open-source', 'attach-reference', 'check-status-later'],
  },
  {
    id: 'bim-fabstation',
    name: 'BIM / FabStation',
    category: 'model-installation',
    status: 'reference-layer',
    sourceOfTruth: 'BIM/FabStation model or installation context',
    nexusRole: 'Rooms, assets, installation sequence, object context, spatial task references and model-linked evidence.',
    objectLinks: ['Asset', 'Room', 'Floor', 'Task', 'Drawing', 'Evidence'],
    actions: ['open-source', 'attach-object-reference', 'link-room-asset-later'],
  },
  {
    id: 'companycam',
    name: 'CompanyCam',
    category: 'photo-evidence',
    status: 'planned',
    sourceOfTruth: 'CompanyCam',
    nexusRole: 'Photo evidence, site visual history and task/inspection proof.',
    objectLinks: ['Evidence', 'Task', 'Project', 'Inspection', 'Approval'],
    actions: ['open-source', 'import-reference-later', 'sync-later'],
  },
  {
    id: 'hilti-assets',
    name: 'Hilti / Assets',
    category: 'asset-management',
    status: 'planned',
    sourceOfTruth: 'Hilti or external asset management system',
    nexusRole: 'Tool, asset, consumable and equipment reference for project tasks and approvals.',
    objectLinks: ['Asset', 'Task', 'Project', 'Evidence'],
    actions: ['open-source', 'attach-asset-reference-later'],
  },
  {
    id: 'microsoft365',
    name: 'Microsoft 365 / SharePoint / OneDrive',
    category: 'office-cloud',
    status: 'planned',
    sourceOfTruth: 'Microsoft 365 tenant, SharePoint or OneDrive',
    nexusRole: 'Enterprise document storage, spreadsheets, emails, Teams context and project file references.',
    objectLinks: ['Project', 'File', 'Document', 'Task', 'Person'],
    actions: ['open-source', 'attach-reference-later', 'sync-later'],
  },
  {
    id: 'gmail-whatsapp',
    name: 'Gmail / WhatsApp',
    category: 'communication-handoff',
    status: 'reference-layer',
    sourceOfTruth: 'User communication apps',
    nexusRole: 'Communication handoff, contact action, message reference and future permission-based project memory.',
    objectLinks: ['Person', 'Company', 'Project', 'Task', 'Evidence'],
    actions: ['open-email', 'open-whatsapp', 'attach-reference-later'],
  },
  {
    id: 'suppliers',
    name: 'Suppliers / Materials',
    category: 'procurement',
    status: 'planned',
    sourceOfTruth: 'Supplier systems, quotes, orders and catalogues',
    nexusRole: 'Material requirements, quote references, purchasing handoff and delivery evidence.',
    objectLinks: ['Project', 'Task', 'File', 'Evidence', 'Approval'],
    actions: ['open-source', 'attach-order-reference-later'],
  },
];

export const getNexusConnector = (id: string) => nexusConnectors.find((connector) => connector.id === id);
