import type { NexusModuleDefinition } from './registryTypes';

export const nexusModules: NexusModuleDefinition[] = [
  {
    id: 'project',
    label: 'PROJECT',
    description: 'Project World control, role context, active project state and graph focus.',
    status: 'prototype',
    dock: true,
    panel: 'ProjectPanel',
    requiredConnectors: [],
    linkedObjects: ['Project', 'ProjectWorld', 'Company', 'Person', 'Task'],
    migrationSource: 'NOSMO-website/apps/nexus-graph-preview/relationship-tree/nexus-project-switcher.js',
  },
  {
    id: 'time',
    label: 'TIME',
    description: 'Project Time instrument, timeline state, replay/simulation mode and project event playback.',
    status: 'prototype',
    dock: true,
    panel: 'ProjectTimePanel',
    requiredConnectors: [],
    linkedObjects: ['Project', 'TimelineEvent', 'Task', 'Evidence', 'Approval'],
    migrationSource: 'NOSMO-website/apps/nexus-graph-preview/relationship-tree/nexus-project-time-instrument.js',
  },
  {
    id: 'people',
    label: 'PEOPLE',
    description: 'People, companies, roles, person cards and project participation context.',
    status: 'prototype',
    dock: true,
    panel: 'PeoplePanel',
    requiredConnectors: [],
    linkedObjects: ['Person', 'Company', 'Project', 'Task', 'Evidence'],
    migrationSource: 'NOSMO-website/apps/nexus-graph-preview/relationship-tree/nexus-people-panel.js',
  },
  {
    id: 'docs',
    label: 'DOCS',
    description: 'Documents, drawings, file loader entry point and project file context.',
    status: 'prototype',
    dock: true,
    panel: 'DocsPanel',
    requiredConnectors: ['google-drive'],
    linkedObjects: ['File', 'Document', 'Drawing', 'Project', 'Task', 'Evidence'],
    migrationSource: 'NOSMO-website/apps/nexus-file-loader',
  },
  {
    id: 'cloud',
    label: 'CLOUD',
    description: 'Nexus Cloud folder map, Google Drive project folders and evidence locations.',
    status: 'prototype',
    dock: true,
    panel: 'CloudPanel',
    requiredConnectors: ['google-drive'],
    linkedObjects: ['ProjectWorld', 'Project', 'File', 'Evidence', 'Document'],
    migrationSource: 'NOSMO-website/apps/nexus-graph-preview/relationship-tree/nexus-cloud-panel.js',
  },
  {
    id: 'soft',
    label: 'SOFT',
    description: 'Software and external system registry: Drive, Work Wallet, BIM/FabStation, CompanyCam, Hilti, Microsoft 365 and supplier systems.',
    status: 'prototype',
    dock: true,
    panel: 'SoftPanel',
    requiredConnectors: ['google-drive', 'work-wallet', 'bim-fabstation', 'companycam', 'microsoft365'],
    linkedObjects: ['Project', 'Person', 'File', 'Evidence', 'Asset', 'Task'],
    migrationSource: 'NOSMO-website/apps/nexus-graph-preview/relationship-tree/nexus-software-panel.js',
  },
  {
    id: 'integrations',
    label: 'INT.',
    description: 'Integration overview and connector readiness view.',
    status: 'prototype',
    dock: true,
    panel: 'IntegrationsPanel',
    requiredConnectors: ['google-drive', 'work-wallet', 'bim-fabstation'],
    linkedObjects: ['Project', 'ProjectWorld', 'File', 'Evidence', 'Task', 'Asset'],
    migrationSource: 'NOSMO-website/apps/nexus-graph-preview/relationship-tree/nexus-integrations-panel.js',
  },
  {
    id: 'evidence',
    label: 'EVIDENCE',
    description: 'Photo/video evidence, inspection proof, task proof and project visual history.',
    status: 'planned',
    dock: true,
    panel: 'EvidencePanel',
    requiredConnectors: ['google-drive', 'companycam'],
    linkedObjects: ['Evidence', 'Task', 'Project', 'Inspection', 'Approval'],
  },
  {
    id: 'doorflow',
    label: 'DOORFLOW',
    description: 'Fire door workflow, door register, door evidence and fire-rated QA/QC process.',
    status: 'prototype',
    dock: false,
    panel: 'DoorFlowPanel',
    requiredConnectors: ['google-drive'],
    linkedObjects: ['Project', 'Drawing', 'File', 'Evidence', 'Inspection', 'Task'],
    migrationSource: 'NOSMO-website/apps/doorflow',
  },
  {
    id: 'fire-door-register',
    label: 'FIRE REGISTER',
    description: 'Manual fire door registration and inspection workflow independent of plan upload.',
    status: 'prototype',
    dock: false,
    panel: 'FireDoorRegisterPanel',
    requiredConnectors: ['google-drive'],
    linkedObjects: ['Inspection', 'Evidence', 'Task', 'Project'],
    migrationSource: 'NOSMO-website/apps/fire-door-register',
  },
  {
    id: 'electrical',
    label: 'ELECTRICAL',
    description: 'Electrical commissioning workflow and completion evidence.',
    status: 'prototype',
    dock: false,
    panel: 'ElectricalPanel',
    requiredConnectors: ['google-drive'],
    linkedObjects: ['Task', 'Evidence', 'Inspection', 'Approval', 'Project'],
    migrationSource: 'NOSMO-website/apps/nexus-graph-preview/electrical-commissioning',
  },
];

export const getNexusModule = (id: string) => nexusModules.find((module) => module.id === id);
